name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  main_project_module: app
  app_name: HangulJamoPlugin

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      
      - name: Build Release APK
        run: ./gradlew assembleRelease
      
      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.app_name }} - Debug APK
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk
      
      - name: Upload Release APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.app_name }} - Release APK
          path: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk
            ${{ env.main_project_module }}/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
